### ISSUE TITLE
Develop Configuration section on the workflows that has set baseDir, threads, cloud Ip

### ISSUE THREAD

**Issue by kekesimarti** [filetrust/cdr-plugin-folder-to-folder#435] opened 2021-05-27 11:00 UTC

**Comment by chrisdiao** [comment] 2021-06-08 08:25
@nishantswarup , may we know the PR for this, please? Kindly link it in this issue is there is any.

**Comment by nishantswarup** [comment] 2021-06-11 07:35
Fixed https://github.com/filetrust/cdr-plugin-folder-to-folder/pull/492

**Comment by MaNe2020** [comment] 2021-06-19 17:47
Duplicate of https://github.com/filetrust/cdr-plugin-folder-to-folder/issues/436 
Will close this one.

**Closed** 2021-07-15 20:17 UTC
Labels: P1, UI, duplicate, v0.11.2
