### ISSUE TITLE
Kubernetes based deployment 

### ISSUE THREAD

**Issue by GINAGC** [filetrust/cdr-plugin-folder-to-folder#562] opened 2021-07-01 04:00 UTC

**Comment by GINAGC** [comment] 2021-07-01 04:00
@chrisdiao this is one issue that we need to review the priority with Dinis.

**Comment by chrisdiao** [comment] 2021-07-01 15:34
got it @GINAGC , will have this in my list for our next discussion with Dinis

**Comment by MaNe2020** [comment] 2021-07-05 00:33
@GINAGC @chrisdiao this is a duplicate of: https://github.com/filetrust/cdr-plugin-folder-to-folder/issues/261

**Closed** 2021-07-15 20:30 UTC
Labels: duplicate
