### ISSUE TITLE
Analyze the reason of the time of pre-process the files 

### ISSUE THREAD

**Issue by kekesimarti** [filetrust/cdr-plugin-folder-to-folder#404] opened 2021-05-20 14:56 UTC
Reported by: Dinis
Hi, please see below a number of screenshots I took on a test run l did yesterday (well early this morning) of the 6.83 GB / 9.7k files from gov.uk

**Some analysis of the images:**

(pic1)  it takes about 6 minutes to pre-process the files (from hd1 to hd2) - where this server was processing about 1400 files per minute (which is still very slow and not really taking advantage of all the compute available in the server)
![image](https://user-images.githubusercontent.com/79467690/119000763-b0a30b00-b98b-11eb-8612-6c98a44c1dff.png)

(pic1, pic2, pic3, pic4), once files are in hd2, and we press 'start' there is another (even slower) step that takes place before any file is sent to the SDKs. You can see this by the average files processed now being about 700 per minute (which is basically something being changed with the files still in the 'Initial' stage). this process takes about 13 minutes (which you can see finally starting at pic4, 21 minutes after the process started)
![image](https://user-images.githubusercontent.com/79467690/119001031-ea741180-b98b-11eb-8556-62064663382f.png)
![image](https://user-images.githubusercontent.com/79467690/119001089-f65fd380-b98b-11eb-8514-7d90ca720210.png)
![image](https://user-images.githubusercontent.com/79467690/119001154-02e42c00-b98c-11eb-89c7-6c6ffc024476.png)

This run was done against the minio version with 5 hot pods, where I was running 60 t3.xlarge servers and 240 threads
With these servers we where averaging about 400 files per minute, 6.6 files per server per minute, and an average process time of ~13 seconds (we really need to look at the performance indicators of the F2F server, since I think this minio version have much more capacity (for example when running just one server I was able to get about 25 files per minute from one server, with 3 to 7 secs process time, which means that I should be able to get about 1500 files per minute with 60 servers)
pic8 shows that the entire processing (of stage 2) took 2,392 seconds, i.e. 39 minutes
![image](https://user-images.githubusercontent.com/79467690/119001232-15f6fc00-b98c-11eb-8fe5-0fe25142c7b3.png)
![image](https://user-images.githubusercontent.com/79467690/119001290-21e2be00-b98c-11eb-830b-b8dcd3308eff.png)
![image](https://user-images.githubusercontent.com/79467690/119001344-2dce8000-b98c-11eb-8f30-cc46e655eed9.png)
![image](https://user-images.githubusercontent.com/79467690/119001396-39ba4200-b98c-11eb-95a0-3c6d92f06ece.png)

**Comment by ggrig** [comment] 2021-05-24 06:06
The latest logs show that preparing the processing plan (hd2/status/hash.json) requires significant time
It may make sense to make the operation multi-threaded to reduce the delay

**Comment by ggrig** [comment] 2021-05-24 13:45
The detailed description of the issue is an exact copy of #405
Marking it as a duplicate

**Comment by ggrig** [comment] 2021-05-25 05:52
This must be fixed in v0.8.5

**Comment by MaNe2020** [comment] 2021-05-25 08:15
@GINAGC this is not for QA, will move it to In Progress and assign to @ggrig 
There is duplicate issue as mentioned on @ggrig comment above

**Comment by GINAGC** [comment] 2021-05-25 13:09
@ggrig is this not ready for QA? I see the tag added with the version and the PR merged, please confirm.

**Comment by ggrig** [comment] 2021-05-28 08:04
@GINAGC 
This is a duplicate of https://github.com/filetrust/cdr-plugin-folder-to-folder/issues/405
The latest currently is in QA. So this one may be closed

**Closed** 2021-07-15 11:29 UTC
Labels: Dev, P2, duplicate, minio, v0.8.5
