### ISSUE TITLE
Develop UI for Processing[ start, stop, load, clear] section

### ISSUE THREAD

**Issue by kekesimarti** [filetrust/cdr-plugin-folder-to-folder#438] opened 2021-05-27 11:05 UTC

**Comment by chrisdiao** [comment] 2021-06-08 08:30
@nishantswarup , may we know the PR for this, please? Kindly link it in this issue if there is any.

**Comment by nishantswarup** [comment] 2021-06-11 07:35
fixed in pr https://github.com/filetrust/cdr-plugin-folder-to-folder/pull/492

**Comment by MaNe2020** [comment] 2021-06-19 17:43
This is the duplicate of: https://github.com/filetrust/cdr-plugin-folder-to-folder/issues/436
Will close this one. @chrisdiao FYI

**Closed** 2021-07-15 20:02 UTC
Labels: P1, UI, duplicate, v0.11.2
