### ISSUE TITLE
Develop an endpoint where user can process a files and get the analysis report back

### ISSUE THREAD

**Issue by chrisdiao** [filetrust/cdr-plugin-folder-to-folder#603] opened 2021-07-13 13:14 UTC

**Comment by MaNe2020** [comment] 2021-07-14 11:40
This is the duplicate of https://github.com/filetrust/cdr-plugin-folder-to-folder/issues/592 will close it. @chrisdiao

**Comment by MaNe2020** [comment] 2021-08-05 10:09
Endpoint present and working: 
![image](https://user-images.githubusercontent.com/70108899/128332803-6f572c5c-a20f-4b72-ab24-88968eb66d35.png)

Opened an issue for documenting this: https://github.com/filetrust/cdr-plugin-folder-to-folder/issues/701

Moving for Release.

**Closed** 2021-08-05 10:53 UTC
Labels: P1, ready-for-qa, v0.16.5
